alertmanager:  
  config:
    route:
      group_by: ['namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'slack-notifications'
      routes:
      - receiver: 'slack-notifications'
        matchers:
          - alertname =~ "InfoInhibitor|Watchdog"
    receivers:
    - name: 'slack-notifications'
      slack_configs:
          - channel: '#kubernetes'
            username: 'Alertmanager'
            api_url: 'https://hooks.slack.com/services/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'
            send_resolved: true
    templates:
    - '/etc/alertmanager/config/*.tmpl'
#prometheus:
 # prometheusSpec:
  #  additionalScrapeConfigs: 
   #   - job_name: 'mongodb-exporter'
    #    static_configs:
     #     - targets: ['mongodb-exporter:9216']
      #  metrics_path: /metrics

    