extraArgs:
  - --collect-all 
  - --compatible-mode
image:
  pullPolicy: IfNotPresent
  repository: bitnami/mongodb-exporter
  tag: "latest"
mongodb:
  uri: "mongodb://mongo:27017"

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  namespace:
  additionalLabels: 
    release: prometheus
