{
 "title": "MongoDB",
 "description": "MongoDB Prometheus Exporter Dashboard. A fork inspired from https://grafana.com/grafana/dashboards/2583 which is made to work well with https://github.com/percona/mongodb_exporter.",
 "tags": [ "prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(mongodb_up, instance)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Node Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAM",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () (container_spec_memory_limit_bytes{node_name=~\"\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}) or \nmax by () (node_memory_MemTotal_bytes{node_name=~\"\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk space",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by () (container_fs_limit_bytes{node_name=~\"\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}) or \navg by () (sum(avg(node_filesystem_size_bytes{node_name=~\"\",fstype=~\"(ext.|xfs|vfat|)\"}) without (mountpoint)) without (device,fstype))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 6, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "clamp_max(avg by () (container_memory_usage_bytes{node_name=~\"\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|backup-agent|\"} * 100 / container_spec_memory_limit_bytes{node_name=\"\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|backup-agent|\"}),100) or  \navg by () (((node_memory_MemAvailable_bytes{node_name=~\"\"} or (node_memory_MemFree_bytes{node_name=~\"\"} + node_memory_Buffers_bytes{node_name=~\"\"} + node_memory_Cached_bytes{node_name=~\"\"})) / node_memory_MemTotal_bytes{node_name=~\"\"}) * 100 or (100 - azure_memory_percent_average{node_name=~\"\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Min Disk Space Available",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by () (min(node_filesystem_free_bytes{node_name=~\"\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"}/node_filesystem_size_bytes{node_name=~\"\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"})*100 or \n(100 - azure_storage_percent_average{node_name=~\"\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "clamp_max(avg(rate(container_cpu_system_seconds_total{node_name=~\"\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[10s])) or \n((avg by () ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"\",mode=\"system\"}[10s]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"\",mode=\"system\"}[5m]),1)) ))*100 or \n(avg_over_time(node_cpu_average{node_name=~\"\", mode=\"system\"}[10s]) or \navg_over_time(node_cpu_average{node_name=~\"\", mode=\"system\"}[5m]))),100)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (node_name,mode) (clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"\",mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[10s]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"\",mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{node_name=~\"\", mode!=\"total\", mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[10s]) or avg_over_time(node_cpu_average{node_name=~\"\", mode!=\"total\", mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[5m]))),100))",
       "legendFormat": "__auto"
      },
      {
       "expr": "clamp_max(sum(rate(container_cpu_usage_seconds_total{node_name=~\"\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[10s]) or rate(container_cpu_usage_seconds_total{node_name=\"\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[5m])) or\nmax by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"\",mode!=\"idle\",mode!=\"iowait\"}[10s]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "__auto"
      },
      {
       "expr": "clamp_max(avg(rate(container_cpu_user_seconds_total{node_name=~\"\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[10s])) or \n((avg by () ((clamp_max(rate(node_cpu_seconds_total{node_name=~\"\",mode=\"user\"}[10s]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"\",mode=\"user\"}[5m]),1)) ))*100 or \n(avg_over_time(node_cpu_average{node_name=~\"\", mode=\"user\"}[10s]) or \navg_over_time(node_cpu_average{node_name=~\"\", mode=\"user\"}[5m]))),100)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Replicaset Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (node_name)  (time() - container_start_time_seconds{node_name=~\"\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}) or avg by (node_name) ((node_time_seconds{node_name=~\"\"} - node_boot_time_seconds{node_name=~\"\"}) or (time() - node_boot_time_seconds{node_name=~\"\"}))"
      }
     ]
    },
    {
     "title": "Available Connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mongodb_connections{instance=~\"$env\",state=\"available\"}"
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 11, "x": 13, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mongodb_connections{instance=~\"$env\",state=\"current\"}"
      }
     ]
    },
    {
     "title": "Member Health",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_replset_number_of_members{instance=~\"$env\"}",
       "legendFormat": "# members"
      },
      {
       "expr": "sum(mongodb_mongod_replset_number_of_members{instance=~\"$env\"})",
       "legendFormat": "healthy members"
      }
     ]
    },
    {
     "title": "Member State",
     "type": "graph",
     "description": "See which node is currently acting as the primary, secondary, ...",
     "gridPos": { "h": 6, "w": 12, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mongodb_rs_members_state{instance=~\"$env\"}",
       "legendFormat": "{{member_state}} - {{member_idx}}"
      }
     ]
    },
    {
     "title": "Replica Query Operations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg by (service_name,type) (rate(mongodb_op_counters_repl_total{service_name=~\"()\"}[5s]) or irate(mongodb_op_counters_repl_total{service_name=~\"()\"}[5m]))",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "avg by (service_name,type) (rate(mongodb_mongod_op_counters_repl_total{service_name=~\"()\"}[5s]) or irate(mongodb_mongod_op_counters_repl_total{service_name=~\"()\"}[5m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (service_name,type) (rate(mongodb_op_counters_total{service_name=~\"()\"}[5s]) or irate(mongodb_op_counters_total{service_name=~\"()\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Metrics for ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "env",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Document Operations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (service_name,state) (rate(mongodb_mongod_metrics_document_total{service_name=~\"()\"}[5s]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"()\"}[5m]))",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Oplog Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "mongodb_oplog_stats_size{instance=~\"$env\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "decmbytes", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "mongodb_memory{instance=~\"$env\",type=~\"resident|virtual\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{node_name=\"\",id=~\"/kubepods/.*\"}[5s]) or \nirate(container_network_transmit_bytes_total{node_name=\"\",id=~\"/kubepods/.*\"}[5m])) or \nsum(rate(node_network_transmit_bytes_total{node_name=\"\", device!=\"lo\"}[5s])) or \nsum(irate(node_network_transmit_bytes_total{node_name=\"\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{node_name=\"\"}[5s])) or \nsum(max_over_time(rdsosmetrics_network_tx{node_name=\"\"}[5m]))",
       "legendFormat": "{{rs_state}}"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{node_name=\"\",id=~\"/kubepods/.*\"}[5s]) or \nirate(container_network_receive_bytes_total{node_name=\"\",id=~\"/kubepods/.*\"}[5m])) or\nsum(rate(node_network_receive_bytes_total{node_name=\"\", device!=\"lo\"}[5s])) or \nsum(irate(node_network_receive_bytes_total{node_name=\"\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_rx{node_name=\"\"}[5s])) or \nsum(max_over_time(rdsosmetrics_network_rx{node_name=\"\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk IO Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
     "targets": [
      {
       "expr": "avg by () (sum(rate(container_fs_reads_bytes_total{node_name=\"\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_reads_bytes_total{node_name=\"\",id=~\"/kubepods.*\"}[5s]))) or\navg by () (rate(node_vmstat_pgpgin{node_name=\"\"}[5s]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"\"}[5m]) * 1024)",
       "legendFormat": "{{device}} - {{instance}}"
      },
      {
       "expr": "avg by () (sum(rate(container_fs_writes_bytes_total{node_name=\"\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_writes_bytes_total{node_name=\"\",id=~\"/kubepods.*\"}[5s]))) or\navg by () ((rate(node_vmstat_pgpgout{node_name=\"\"}[5s]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"\"}[5m]) * 1024))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by () (sum(rate(container_fs_reads_bytes_total{node_name=\"\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_reads_bytes_total{node_name=\"\",id=~\"/kubepods.*\"}[5s]))) + \navg by () (sum(rate(container_fs_writes_bytes_total{node_name=\"\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_writes_bytes_total{node_name=\"\",id=~\"/kubepods.*\"}[5s]))) or \navg  by () ((rate(node_vmstat_pgpgin{node_name=\"\"}[5s]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"\"}[5m]) * 1024 ) + (rate(container_fs_writes_bytes_total{node_name=\"\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_writes_bytes_total{node_name=\"\",id=~\"/kubepods.*\"}[5s]))) + \navg by () (sum(rate(container_fs_writes_bytes_total{node_name=\"\",id=~\"/kubepods.*\"}[5s]) or irate(container_fs_writes_bytes_total{node_name=\"\",id=~\"/kubepods.*\"}[5s]))) or \navg  by () ((rate(node_vmstat_pgpgout{node_name=\"\"}[5s]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"\"}[5m]) * 1024))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpin{node_name=\"\"}[5s]) * 4096 or irate(node_vmstat_pswpin{node_name=\"\"}[5m]) * 4096)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by () (rate(container_memory_swap{node_name=\"\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[5s]) or \nirate(container_memory_swap{node_name=\"\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|\"}[5s])) or \navg by () (rate(node_vmstat_pswpout{node_name=\"\"}[5s]) * 4096 or \nirate(node_vmstat_pswpout{node_name=\"\"}[5m]) * 4096)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}