apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gke-storage  # Use the StorageClass you created
  resources:
    requests:
      storage: 10Gi  # Specify the size you need
